
[[constraint]]
  name = "github.com/burntsushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "~1.4.5"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "~1.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-gatedio"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-rootcerts"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-syslog"

[[constraint]]
  name = "github.com/hashicorp/hcl"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/logutils"

[[constraint]]
  name = "github.com/mattn/go-shellwords"
  version = "1.0.3"

[[constraint]]
  name = "github.com/hashicorp/go-hclog"
  revision = "4783caec6f2e5cdd47fab8b2bb47ce2ce5c546b7"

[[override]]
  name = "github.com/mgutz/logxi"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
